In [1]:
import numpy as np
from numpy import linalg as la

N = int(input("Enter the dimension of data : ")) 
n = int(input("Number of data points : "))

X = [[0 for a in range(n)] for b in range(N)]
print(np.shape(X))

print("Covarience is : ")
C = np.cov(X,ddof=0)
print(C)

#Eigen values and vectors
w, v = la.eig(C)
print("Eigen values")
print(w)
print("Eigen Vectors")
print(v)
print("Index of Eigen value to be discarded: ")
idx = int(input())
A_new = np.delete(v,(idx),axis=0)
X = np.array(X)
x_new = []
x_new = np.array(x_new)
x = []
x = np.array(x)
y = np.zeros((2,2))
y = np.array(y)
res = [[0 for a in range(n)] for b in range(N)]
res = np.array(res)
for i in range (n):
    x = X[:,i]
    x = np.array(x)
    x = x .T
    y = np.dot(A_new,x)
    x_new = np.array(A_new).T * y
    x_new = np.array(x_new.T)
    x_new = x_new.T
    res = np.append(res,x_new,axis=1)
for j in range (n):
    res = np.delete(res,(0),axis=1)

Enter the dimension of data : 2
Number of data points : 8
(2, 8)
Covarience is : 
[[0. 0.]
 [0. 0.]]
Eigen values
[0. 0.]
Eigen Vectors
[[1. 0.]
 [0. 1.]]
Index of Eigen value to be discarded: 
0


In [2]:
res

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [3]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [4]:
E = (X-res)**2
E = np.sum(E,axis=1)/8
E = np.sum(E,axis=0)
E

0.0